#pragma once
#include <Magick++.h>
#include "defocusBlur.h"
#include "motionBlur.h"
#include "convolve.h"
#include "uni_grain.h"
#include "jPegger.h"
#include "util.hpp"
#include <cxxopts.hpp>
#include <algorithm>
#include <cmath>
#include <fstream>
#include <streambuf>
#include <list>
#include <iomanip>
#include <string>
#include <iostream>
#include <regex>
#include <cstdlib>
#include <ctime>
#include <random>
#include <cstdio>
#include <algorithm>
#include <filesystem>
#include <map>
#include <ios>
